name: CI
on:
  pull_request:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main
permissions: read-all
jobs:
  affected:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      NX_CLOUD_CONTINUOUS_ASSIGNMENT: true
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5.0.1
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build,lint,test,typecheck"
      - run: pnpm exec nx affected -t build,lint,test,typecheck --base="$NX_BASE" --head="$NX_HEAD"
      - run: npx nx-cloud record -- pnpm run format:check
      - run: npx nx-cloud record -- pnpm run lint:workspace
      - run: npx nx-cloud fix-ci
        if: always()
